### ISSUE TITLE
Object Oriented Programming in Java and Data Structures and Performance Classes are Outdated

### ISSUE THREAD

**Issue by KatalystDev** [ForrestKnight/open-source-cs#37]
Both of these courses use applets which haven't been supported since java version 8 and apparently the code they provide is still buggy when you use version 8. It looks like the the next "Java Programming" course teaches much the same things as the Object Oriented Programming course but without the GUI. Maybe this course should be replaced with another Java course that implements GUI design.

**Comment by flyingsl0ths** [comment]
So does java Programming principles of software and design 

Data structures and performance was the only one that teaches something new the rest of the java courses can be replaced by the java Helsinki mooc part 1

**Comment by KatalystDev** [comment]
> So does java Programming principles of software and design
> 
> Data structures and performance was the only one that teaches something new the rest of the java courses can be replaced by the java Helsinki mooc part 1 and the recommendation system course by a project made by the actual student (speaking from experience this is what i did I now have a good grasp on java)

I've already taken the first two courses from duke for Java so then what order would you recommend the next two classes. Data structures and performance then the Helsinki mooc part 1? Then I'm guessing the personal project?

**Comment by flyingsl0ths** [comment]
Here's what I did since I had some prior programming experience I skipped the Duke courses as they seemed repetitive and I got bored

First:
I watched the first 30 videos of Derek Banas java tutorial playlist on YouTube

Second: did the first part of the Helsinki mooc

Third:
Made a project 

Fourth:
Finished Data structures and performance course (current on Programming languages part A really good course btw)
